#!/usr/bin/env bash

read -ep "Favorite color? " -i "Blue" favcolor
echo $favcolor


#!/usr/bin/env bash

if (($#<3)); then
    echo "This command requires three arguments:"
    echo "username, userid, and favorite number."
else
    # the program goes here
    echo "username: $1"
    echo "userid: $2"
    echo "favorite number: $3"
fi


#!/usr/bin/env bash

read -p "Favorite animal? " fav
while [[ -z $fav ]] # '-z' is use to check if var fav is not empty
do
        read -p "I need an answer! " fav
done

echo "$fav was selected."


#!/usr/bin/env bash

read -p "Favorite animal? [cat] " fav # Notice the bracket after the prompt?
if [[ -z $fav ]]; then
        fav="cat"
fi
echo "$fav was selected"


#!/usr/bin/env bash

read -p "What year? [nnnn] " year
until [[ $year =~ [0-9]{4} ]]; do
        read -p "A year, please! [nnnn] " year
done
echo "Selected year: $year"
