#!/usr/bin/env bash

for i in 1 2 3
do
    echo $i
done

for i in 1 2 3; do echo $i; done


#!/usr/bin/env bash

for i in {1..100}
do
    echo $i
done


#!/usr/bin/env bash

for (( i=1; i<=100; i++ ))
do
    echo $i
done


#!/usr/bin/env bash

declare -a fruits=("apple" "banana" "cherry")
for i in ${fruits[@]}
do
    echo $i
done



#!/usr/bin/env bash

declare -A arr
arr["name"]="scott"
arr["id"]="1234"
for i in "${!arr[@]}" # for associative array, added quote and '!' like this
do
    echo $i: "${arr[$i]}"
done



#!/usr/bin/env bash

for i in $(ls)
do
    echo "Found a file: $i"
done



#!/usr/bin/env bash

for i in * # set i to the name of each item in the current directory
do
    echo "Found a file: $i"
done