#!/usr/bin/env bash

declare -i a=3

if [[ $a -gt 4 ]]; then # Could use arithmatic evaluation too (($a>4))
    echo "$a is greater than 4!"
elif (( $a > 2 ))
then
    echo "$a is greater than 2."
else
    echo "$a is not greater than 4!"
fi